name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking-change'

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
template: |
  ## ✨ Nouveautés de la version $RESOLVED_VERSION

  $CHANGES

  ---
  *Release générée automatiquement par [Release Drafter](https://github.com/marketplace/actions/release-drafter).*
